#  =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-  #
#                        -------- Welcome to the BlockBoost Config --------
# -
# If this is your first time setting up, please refer to the example_config.yml for a detailed
# explanation of each block type set up.
# -
#  =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-  #
#                          -------- Global BlockBoost Settings --------
#  =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-  #
# Display block creation on plugin start or reload
console-messages:
  bounce-blocks: true
  command-blocks: true
  potion-blocks: true
  speed-blocks: true

#  =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-  #
#                          -------- BlockBoost Block Setup --------
#  =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-  #
bounce-blocks:
#  EXAMPLE_BLOCK:
#    world: global
#    include-world: true
#    height: 0
#    normalize: true

explosion-blocks:
#  EXAMPLE_BLOCK:
#    power: 2.0
#    set-fire: false
#    break-blocks: true
#    player-damage: 4.0
#    player-kill: false

command-blocks:
#  EXAMPLE_BLOCK:
#    world: global
#    include-world: true
#    console-sender: true
#    command: bbspeed %PLAYERNAME% 0.2
#    permission: bb.use

particle-blocks:

potion-blocks:
#  EXAMPLE_BLOCK:
#    world: global
#    include-world: true
#    effect: POTION_EFFECT_TYPE
#    duration: 1
#    amplifier: 1

speed-blocks:
#  EXAMPLE_BLOCK:
#    world: global
#    include-world: true
#    type: MULTIPLIER
#    amount: 1.5
#    cap: 1.0
#    duration: 5
#    cooldown: 10

